TurbSim Input File. Valid for TurbSim v1.06.00a-bjj, 30-Jul-2012.
Input file generated by ..\GenTurb_39x37.pl on 07-Oct-2014 at 14:50:18.
---------Runtime Options-----------------------------------
202             RandSeed1
RANLUX          RandSeed2
False           WrBHHTP
False           WrFHHTP
False           WrADHH
True            WrADFF
FALSE           WrBLFF
False           WrADTWR
False           WrFMTFF
False           WrACT
True            Clockwise
1               ScaleIEC
True            Periodic

--------Turbine/Model Specifications-----------------------
7               NumGrid_Z
9               NumGrid_Y
0.05            TimeStep
360             AnalysisTime
360             UsableTime
98.189          HubHt
30              GridHeight
40              GridWidth
0               VFlowAng
0               HFlowAng

--------Meteorological Boundary Conditions-------------------
"IECKAI"        TurbModel
"3"             IECstandard
c               IECturbc
NTM             IEC_WindType
default         ETMc
"IEC"           WindProfileType
98.189          RefHt
14              URef
default         ZJetMax
0.14            PLExp
default         Z0

--------Non-IEC Meteorological Boundary Conditions------------
default         Latitude
0.05            RICH_NO
default         UStar
default         ZI
default         PC_UW
default         PC_UV
default         PC_VW
default         IncDec1
default         IncDec2
default         IncDec3
default         CohExp

--------Coherent Turbulence Scaling Parameters----------------
""              CTEventPath
"Random"        CTEventFile
true            Randomize
1.0             DistScl
0.5             CTLy
0.5             CTLz
30.0            CTStartTime
